### ISSUE TITLE
DB fix

### ISSUE THREAD

**Issue by AdrineX** [FXServer-ESX/fxserver-esx_jobs#1]
jobs.sql

INSERT INTO `jobs` (`name`, `label`) VALUES
('unemployed', 'Chômeur'),
('slaughterer', 'Abatteur'),
('fisherman', 'Pêcheur'),
('miner', 'Mineur'),
('lumberjack', 'Bûcheron'),
('fuel', 'Raffineur'),
('reporter', 'Journaliste'),
('textil', 'Couturier');

job_grades.sql

INSERT INTO `job_grades` (`job_name`, `grade`, `name`, `label`, `salary`, `skin_male`, `skin_female`) VALUES
('unemployed', 0, 'rsa', 'RSA', 0, '{}', '{}'),
('lumberjack', 0, 'interim', 'Intérimaire', 0, '{}', '{}'),
('fisherman', 0, 'interim', 'Intérimaire', 0, '{}', '{}'),
('fuel', 0, 'interim', 'Intérimaire', 0, '{}', '{}'),
('reporter', 0, 'employee', 'Intérimaire', 0, '{}', '{}'),
('textil', 0, 'interim', 'Intérimaire', 0, '{}', '{}'),
('miner', 0, 'interim', 'Intérimaire', 0, '{}', '{}'),
('slaughterer', 0, 'interim', 'Intérimaire', 0, '{}', '{}');

**Comment by indilo53** [comment]
Thank you
