### ISSUE TITLE
bad argument #1 to 'pairs' (table expected, got nil)

### ISSUE THREAD

**Issue by edgegamers** [FXServer-ESX/fxserver-esx_jobs#2]
[    815719] Error resuming coroutine: client/esx_jobs_cl.lua:442: bad argument #1 to 'pairs' (table expected, got nil)
[    815719] stack traceback:
[    815719] 	[C]: in function 'pairs'
[    815719] 	client/esx_jobs_cl.lua:442: in function <client/esx_jobs_cl.lua:422>

**Comment by indilo53** [comment]
What you were trying to do when you had this error ?

**Comment by hoslety** [comment]
I have the same error when I connect
