### ISSUE TITLE
Probleme de vente pour le job : Abatteur / mineur

### ISSUE THREAD

**Issue by nmaroine** [FXServer-ESX/fxserver-esx_jobs#6]
Bonjour,
pour le job abatteur, on ne peux pas vendre les barquette de poulet, voici les logs d'erreurs : 

![image](https://user-images.githubusercontent.com/17453646/29525114-f4f1ed16-8691-11e7-8896-8f7bb9437961.png)

Edit : je viens de tester avec le mineur ça ne marche pas non plus
je vous remercie d'avance

**Comment by ddh3** [comment]
Please test now. Should be fixed..

**Comment by nmaroine** [comment]
i confirm, it's fixed, thank you again for the help you are providing to the GTA RP community
